# Generated by Django 4.1.3 on 2022-12-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_funcionario_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criados",
                    models.DateField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("recurso", models.CharField(max_length=150, verbose_name="Recurso")),
                (
                    "descricao",
                    models.TextField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "icone",
                    models.CharField(
                        choices=[
                            ("lni-layers", "Design"),
                            ("lni-leaf", "Folha"),
                            ("lni-cog", "Emgrenagem"),
                            ("lni-laptop-phone", "Notebook"),
                            ("lni-rocket", "Foguete"),
                        ],
                        max_length=16,
                        verbose_name="Icone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
    ]
